// Builds the installable web app (PWA) into dist/ for GitHub Pages.
//   npm run build:web
// Steps: expo export, then patch index.html for the iPhone home screen,
// write a service worker that precaches every file, and add the files
// GitHub Pages needs (404.html for client-side routes, .nojekyll for _expo/).
import { execSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { copyFileSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const DIST = 'dist';
const app = JSON.parse(readFileSync('app.json', 'utf8')).expo;
const BASE = app.experiments?.baseUrl ?? '';

execSync('npx expo export --platform web --clear', { stdio: 'inherit' });

const HEAD = `
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="apple-mobile-web-app-title" content="Routine">
<meta name="color-scheme" content="light dark">
<link rel="manifest" href="${BASE}/manifest.webmanifest">
<link rel="apple-touch-icon" href="${BASE}/icons/apple-touch-icon.png">
<style>
  html, body { background: #ffffff; }
  @media (prefers-color-scheme: dark) { html, body { background: #000000; } }
</style>
<script>
  if ('serviceWorker' in navigator) {
    window.addEventListener('load', function () {
      navigator.serviceWorker.register('${BASE}/sw.js', { scope: '${BASE}/' });
    });
  }
</script>
`;

const indexPath = join(DIST, 'index.html');
let html = readFileSync(indexPath, 'utf8');
html = html.replace(
  /<meta name="viewport"[^>]*>/,
  '<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, viewport-fit=cover" />'
);
html = html.replace('</head>', `${HEAD}</head>`);
writeFileSync(indexPath, html);
copyFileSync(indexPath, join(DIST, '404.html'));
writeFileSync(join(DIST, '.nojekyll'), '');

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const p = join(dir, name);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

const files = walk(DIST)
  .map((p) => relative(DIST, p).split('\\').join('/'))
  .filter((f) => !['sw.js', '404.html', '.nojekyll', 'metadata.json'].includes(f));

const hash = createHash('sha256');
for (const f of files.sort()) hash.update(f).update(readFileSync(join(DIST, f)));
const version = hash.digest('hex').slice(0, 12);

const precache = [`${BASE}/`, ...files.map((f) => `${BASE}/${f}`)];

writeFileSync(
  join(DIST, 'sw.js'),
  `// Generated by scripts/build-web.mjs. Do not edit.
const CACHE = 'routine-${version}';
const PRECACHE = ${JSON.stringify(precache, null, 2)};
const INDEX = '${BASE}/index.html';

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  if (req.mode === 'navigate') {
    // App shell: network first so a new version arrives, cache when offline.
    event.respondWith(
      fetch(req).catch(() => caches.match(INDEX, { ignoreSearch: true }))
    );
    return;
  }
  // Hashed bundles and static files: cache first.
  event.respondWith(caches.match(req).then((hit) => hit || fetch(req)));
});
`
);

console.log(`\nweb build ready: ${files.length} files precached, version ${version}, base "${BASE}"`);
